<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="action.surefire.report.calc.StringUtilsTest" time="0.01" tests="5" errors="0" skipped="1" failures="2">
  <testcase name="require_failMsg" classname="action.surefire.report.calc.StringUtilsTest" time="0"/>
  <testcase name="require_fail" classname="action.surefire.report.calc.StringUtilsTest" time="0.007">
    <failure message="&#10;Expected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing &quot;This is unexpected&quot;)&#10;     but: exception with message a string containing &quot;This is unexpected&quot; message was &quot;Input=&apos;&apos; didn&apos;t match condition.&quot;&#10;Stacktrace was: java.lang.IllegalArgumentException: Input=&apos;&apos; didn&apos;t match condition.&#10;	at action.surefire.report.calc.StringUtils.requireNotBlank(StringUtils.java:25)&#10;	at action.surefire.report.calc.StringUtils.requireNotBlank(StringUtils.java:18)&#10;	at action.surefire.report.calc.StringUtilsTest.require_fail(StringUtilsTest.java:27)&#10;	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#10;	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#10;	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#10;	at java.lang.reflect.Method.invoke(Method.java:498)&#10;	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)&#10;	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#10;	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)&#10;	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#10;	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)&#10;	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)&#10;	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)&#10;	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)&#10;	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)&#10;	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)&#10;	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)&#10;	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)&#10;	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)&#10;	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)&#10;	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)&#10;	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)&#10;	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)&#10;	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)&#10;	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)&#10;	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)&#10;	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)&#10;	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)&#10;	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)&#10;	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)&#10;	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)&#10;" type="java.lang.AssertionError">java.lang.AssertionError: 

Expected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing "This is unexpected")
     but: exception with message a string containing "This is unexpected" message was "Input='' didn't match condition."
Stacktrace was: java.lang.IllegalArgumentException: Input='' didn't match condition.
	at action.surefire.report.calc.StringUtils.requireNotBlank(StringUtils.java:25)
	at action.surefire.report.calc.StringUtils.requireNotBlank(StringUtils.java:18)
	at action.surefire.report.calc.StringUtilsTest.require_fail(StringUtilsTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</failure>
  </testcase>
  <testcase name="require_withNullMsg" classname="action.surefire.report.calc.StringUtilsTest" time="0"/>
  <testcase name="require" classname="action.surefire.report.calc.StringUtilsTest" time="0">
    <failure type="java.lang.AssertionError">java.lang.AssertionError
	at action.surefire.report.calc.StringUtilsTest.require(StringUtilsTest.java:20)
</failure>
  </testcase>
  <testcase name="require_fail_null" classname="action.surefire.report.calc.StringUtilsTest" time="0">
    <skipped/>
  </testcase>
</testsuite>